// 全部中文文案集中于此，界面零硬编码。

export const STR = {
  appName: '干瞪眼',
  lobby: {
    title: '干瞪眼',
    subtitle: '三副牌 · 2-6 人 · 带角色技能',
    nameLabel: '玩家名',
    namePlaceholder: '输入昵称（12 字内）',
    create: '创建房间',
    join: '加入房间',
    codePlaceholder: '6 位房间号',
    scores: '战绩',
    connecting: '连接中…',
    offline: '服务器未连接',
    online: '已连接',
  },
  room: {
    title: '房间',
    copy: '复制',
    copied: '已复制房间号',
    waitHost: '等待房主开始…',
    canStart: '开始游戏',
    startHint: {
      notHost: '只有房主能开始',
      tooFew: '至少需要 2 人',
      notAllReady: '等待所有人准备并选好角色',
    },
    ready: '准备',
    cancelReady: '取消准备',
    needRoleFirst: '先选角色',
    readyState: '已准备',
    leave: '离开房间',
    selectRole: '选择你的角色',
    roleTaken: '已被 {name} 选择',
    roleYours: '已选择',
    lockedSkill: '·锁定技',
    you: '你',
    host: '房主',
    offlineBadge: '掉线',
    mySeat: '我的座位',
  },
  game: {
    yourTurn: '你的回合',
    turnOf: '轮到 {name}',
    waiting: '等待中…',
    play: '出牌',
    pass: '过',
    passConfirm: '确认过牌？',
    passAgain: '已取消选牌，再点一次「过」确认',
    cannotPassLeader: '新一轮起牌者必须出牌',
    deckLeft: '牌堆 {n}',
    discard: '弃 {n}',
    leave: '离开',
    beatWarn: '{hint}（技能可能豁免）',
    passed: '过',
    tableEmpty: '等待出牌',
    orderReversed: '倒序',
    reconnect: '连接已断开，正在重连…',
    skillToast: '【{skill}】{text}',
    roundEndToast: '无人能管，{name} 摸 {n} 张继续出',
    curseBadge: '红楼梦',
    curseTakeover: '【地坛】{name} 取而代之，摸 {n} 张继续出',
    drawnToast: '{name} 摸了 {n} 张牌',
    winnerTitle: '{name} 获胜！',
    drawTitle: '流局（无人能出牌）',
    scoreTitle: '本局记分',
    totalLabel: '累计',
    rematch: '再来一局',
    rematchVoted: '已投票（{voted}/{total}）',
    rematchWaiting: '等待其他人投票（{voted}/{total}），全员同意后回房间重新选角色',
    backLobby: '返回大厅',
    leaveRoom: '离开房间',
    skillAsk: '技能询问',
    confirm: '确定',
    decline: '放弃',
    submit: '提交',
    cutInHint: '选择接牌组合（需含与被压牌相同花色的真牌）',
    selfFollowHint: '选择要压的牌（按正常管牌规则，可连压）',
    retagFrom: '改判：原{label}',
    retagTitle: '修勾答疑：这手牌按新点数判定',
    pickHint: '已选 {n} 张（需 {min}-{max} 张）',
    pickHiddenHint: '盲抽只看牌背：已选 {n} 张（需 {min}-{max} 张）',
    cardBack: '牌背（盲抽）',
    eliminated: '已淘汰',
    eliminatedToast: '{name} 被淘汰（{reason}）',
    revealedToast: '{name} 亮出 {n} 张牌：{purpose}',
    revealPanel: '翻开的牌（{purpose}）',
    organize: '整理',
    sortRank: '点数序',
    sortSuit: '花色序',
    sortColor: '颜色序',
    organizeHint: '点两张牌交换位置',
    skillReady: '可发动',
  },
  scoreboard: {
    title: '战绩',
    back: '返回',
    empty: '还没有战绩记录',
    time: '时间',
    room: '房间',
    winner: '赢家',
    players: '玩家',
    draw: '流局',
    scoreLabel: '分',
  },
  common: {
    error: '出错了',
    ok: '确定',
    cancel: '取消',
  },
} as const;

/** 玩家名 localStorage 键 */
export const LS_NAME = 'gdys-name';
/** 重连身份 localStorage 键：{roomId, playerId, secret} */
export const LS_IDENTITY = 'gdys-identity';

/** 回合倒计时（秒），与服务端掉线自动过时长一致 */
export const TURN_SECONDS = 30;
