// 全部中文文案集中于此，界面零硬编码。

export const STR = {
  appName: '干瞪眼',
  lobby: {
    title: '干瞪眼',
    subtitle: '三副牌 · 2-6 人 · 带角色技能',
    nameLabel: '玩家名',
    namePlaceholder: '输入昵称（12 字内）',
    create: '创建房间',
    join: '加入房间',
    codePlaceholder: '6 位房间号',
    scores: '战绩',
    connecting: '连接中…',
    offline: '服务器未连接',
    online: '已连接',
  },
  room: {
    title: '房间',
    copy: '复制',
    copied: '已复制房间号',
    waitHost: '等待房主开始…',
    canStart: '开始游戏',
    noRole: '未选角色',
    startHint: {
      notHost: '只有房主能开始',
      tooFew: '至少需要 2 人',
      notAllReady: '等待所有人准备并选好角色',
    },
    ready: '准备',
    cancelReady: '取消准备',
    needRoleFirst: '先选角色',
    readyState: '已准备',
    leave: '离开房间',
    selectRole: '选择你的角色',
    roleTaken: '已被 {name} 选择',
    roleYours: '已选择',
    lockedSkill: '·锁定技',
    you: '你',
    host: '房主',
    offlineBadge: '掉线',
    mySeat: '我的座位',
  },
  game: {
    yourTurn: '你的回合',
    turnOf: '轮到 {name}',
    waiting: '等待中…',
    play: '出牌',
    pass: '过',
    passConfirm: '确认过牌？',
    passAgain: '已取消选牌，再点一次「过」确认',
    cannotPassLeader: '新一轮起牌者必须出牌',
    deckLeft: '牌堆 {n}',
    discard: '弃 {n}',
    leave: '离开',
    beatWarn: '{hint}（技能可能豁免）',
    passed: '过',
    tableEmpty: '等待出牌',
    orderReversed: '倒序',
    orderBadgeTitle: '海棠洄游：整条牌序反转中',
    reconnect: '连接已断开，正在重连…',
    defaultRevealPurpose: '翻牌',
    revealedMore: '（共 {n} 张）',
    pancakeTitle: '饼：倒置的牌，任何人不可看牌面、不可使用',
    handPickHint: '点选手牌（王可补缺）',
    opponentFallback: '对方',
    seatRoleUnknown: '?',
    seatLeader: '起牌',
    seatAsking: '询问中',
    seatPrev: '上家',
    seatNext: '下家',
    seatAcross: '对面',
    seatAdjacent: '上/下家',
    curseActiveTitle: '红楼梦：本回合不得出牌',
    cursePendingTitle: '红楼梦：下一轮不得出牌',
    jianxiTitle: '见习罚站：本回合不得出牌、不被技能响应',
    jianxiBadge: '见习',
    retagTitleNote: '修勾答疑：按 {rank} 点判定（原 {label}）',
    seatHandTitle: '{name} 手牌 {n} 张',
    pickTargetLabel: '{name}（{n} 张）',
    handUnknown: '??',
    privateZoneTitle: '辛歼（神秘）：只属于你自己的独立牌堆与弃牌堆',
    privateDeck: '私有牌堆 {n} 张',
    privateDiscard: '私有弃牌 {n} 张',
    comboBack: '背',
    comboWild: '鬼',
    cardJokerLabel: '王',
    cardJokerBig: '大',
    cardJokerSmall: '小',
    cardAsRank: '当{label}',
    /** 出牌预览提示（beatHint.ts 用；客户端零硬编码） */
    preview: {
      jokerAlone: '王不能单独打出',
      invalidCombo: '这不是合法牌型',
      noFinish2: '不能以单2/对2打完手牌',
      noFinish3: '不能以单3/对3打完手牌（倒序禁止收尾）',
      bombOnly: '只有炸弹能压炸弹',
      bombNotEnough: '炸弹张数不够',
      bombTooSmall: '炸弹点数不够小（倒序比点反转）',
      bombTooBig: '炸弹点数不够大',
      typeMismatch: '牌型不同，无法压',
      onlyBombBeats2: '只有炸弹能压 2',
      onlyBombBeats3: '只有炸弹能压 3',
      mustUp1: '必须恰好大一点（出 {kind}{label}）',
      mustDown1: '必须恰好小一级（出 {kind}{label}）',
      kindPair: '对',
      straightLen: '顺子长度必须相同',
      cpLen: '连对长度必须相同',
      needHigher: '起点必须比上家大',
      needHigherRev: '接牌最高点必须比上家大（倒序）',
      outOfWindow: '起点超出接牌窗口',
      babyBlocked: '【温柔】宝贝本回合不得响应组长的出牌',
    },
    skillToast: '【{skill}】{text}',
    roundEndToast: '无人能管，{name} 摸 {n} 张继续出',
    curseBadge: '红楼梦',
    curseTakeover: '【地坛】{name} 取而代之，摸 {n} 张继续出',
    drawnToast: '{name} 摸了 {n} 张牌',
    winnerTitle: '{name} 获胜！',
    drawTitle: '流局（无人能出牌）',
    scoreTitle: '本局记分',
    totalLabel: '累计',
    rematch: '再来一局',
    rematchVoted: '已投票（{voted}/{total}）',
    rematchWaiting: '等待其他人投票（{voted}/{total}），全员同意后回房间重新选角色',
    backLobby: '返回大厅',
    leaveRoom: '离开房间',
    skillAsk: '技能询问',
    confirm: '确定',
    decline: '放弃',
    submit: '提交',
    cutInHint: '选择接牌组合（需含与被压牌相同花色的真牌）',
    selfFollowHint: '选择要压的牌（按正常管牌规则，可连压）',
    proxyPlayHint: '选择要打的牌（按正常管牌规则，打出视作硝烟打出）',
    declineProxy: '不出（走惩罚）',
    retagFrom: '改判：原{label}',
    retagTitle: '修勾答疑：这手牌按新点数判定',
    pickHint: '已选 {n} 张（需 {min}-{max} 张）',
    guessHint: '猜对方手牌数（{min}-{max} 张；猜中技能照常生效并摸 1-3 张，猜错技能失效）',
    pickHiddenHint: '盲抽只看牌背：已选 {n} 张（需 {min}-{max} 张）',
    cardBack: '牌背（盲抽）',
    eliminated: '已淘汰',
    eliminatedToast: '{name} 被淘汰（{reason}）',
    eliminatedBanner: '{name} 被淘汰',
    revealedToast: '{name} 亮出 {n} 张牌：{purpose}',
    revealPanel: '翻开的牌（{purpose}）',
    organize: '整理',
    sortRank: '点数序',
    sortSuit: '花色序',
    sortColor: '颜色序',
    organizeHint: '点两张牌交换位置',
    skillReady: '可发动',
    flipHint: '端庄：点桌面一张牌翻面，再选要出的牌',
    flipPicked: '已翻面 {label}，选要出的牌（接不上可「过」，翻面自动复原）',
    flipPickCards: '请选择要出的牌（或「过」放弃翻面）',
    flipSuggest: '｜端庄：点桌面一张牌翻面再出',
    peekedToast: '{name} 查看了你的手牌',
    ouYaHint: '【呕哑】已包含桌面所有点数，无视管牌规则',
    rfRestrict: '【吐饼】无牌权时只能打出 {rank} 或炸弹（恰好接上的牌请走吃饼询问）',
    rfNoPass: '【吐饼】吃过饼不能过：只能打 {rank} 或炸弹',
    pancakeBadge: '🍪{n}',
    deckRecycled: '牌堆已空：弃牌堆洗回牌堆（{n} 张）',
    peekTitle: '【窃笑】{name} 的手牌',
    peekClose: '关闭',
    roundHistoryTitle: '本回合出牌记录（回合结束统一弃置）',
    roundHistoryEmpty: '本回合暂无出牌',
    pileTitle: '本回合打出的牌（回合结束统一弃置）',
    judgedTitle: '判定牌（回合结束统一弃置）',
    judgedLabel: '判定',
    discardStageTitle: '本回合公开弃置的牌（轮末进弃牌堆）',
    discardStageLabel: '弃牌',
    heldBadge: '🪧扣置',
    heldViewTitle: '【尖叫】扣置牌',
    heldViewHint: '点击查看/收回扣置牌',
    heldTakeBack: '收回',
    heldPutBack: '放回',
    heldTakeBackHint: '全部收回手牌（不消耗次数）',
    heldPutBackHint: '保持扣置（继续生效）',
    heldAskBusy: '有技能询问进行中，暂不能收回',
    heldFanwen: '范文',
    heldJianjiaoji: '尖叫鸡',
    heldGroupLine: '{kind} {n} 张',
    heldTipTitle: '{name} 的扣置牌',
    roleTitle: '{name} · {role}',
    viewSkills: '查看技能',
  },
  scoreboard: {
    title: '战绩',
    back: '返回',
    empty: '还没有战绩记录',
    time: '时间',
    timeFormat: '{m}/{d} {h}:{min}',
    room: '房间',
    winner: '赢家',
    players: '玩家',
    draw: '流局',
    scoreLabel: '分',
  },
  common: {
    error: '出错了',
    ok: '确定',
    cancel: '取消',
    loading: '…',
    requestTimeout: '请求超时',
  },
} as const;

/** 玩家名 localStorage 键 */
export const LS_NAME = 'gdys-name';
/** 重连身份 localStorage 键：{roomId, playerId, secret} */
export const LS_IDENTITY = 'gdys-identity';

/** 回合倒计时（秒），与服务端掉线自动过时长一致 */
export const TURN_SECONDS = 30;
